sudo: required
dist: trusty
language: cpp
cache: ccache

env:
  - QT=qt58

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev
  - if [[ "$QT" == "qt58" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt58-trusty; sudo apt-get update -qq; sudo apt-get install -qq qt58tools qt58script qt58webengine qt58webchannel qt58declarative qt58x11extras; fi

script:
  - QMAKE="qmake"
  - if [[ "$QT" == "qt58" ]]; then QMAKE="/opt/qt58/bin/qmake"; fi
  - $QMAKE QMAKE_CXXFLAGS+="-Wextra -Werror"
  - make -j2 || exit 1
  - cd scripts && ./run_tests.sh $QMAKE
